name: Juice Shop Security Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Pull Juice Shop Docker image
      run: docker pull bkimminich/juice-shop

    - name: Run Juice Shop container
      run: docker run -d -p 3000:3000 bkimminich/juice-shop

    - name: Wait for Juice Shop to start
      run: sleep 15

    - name: Verify Juice Shop is running
      run: curl -I http://localhost:3000

    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install wget -y
        wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.50.0_Linux-64bit.deb

    - name: Scan Docker image with Trivy
      run: trivy image bkimminich/juice-shop
